#!/bin/sh

bat=/sys/class/power_supply/BAT0/
per="$(cat "$bat/capacity")"

icon() {

[ $(cat "$bat/status") = Charging ] && echo "" && exit

if [ "$per" -gt "80" ]; then
	icon=""
elif [ "$per" -gt "65" ]; then
	icon=""
elif [ "$per" -gt "45" ]; then
	icon=""
elif [ "$per" -gt "15" ]; then
	icon=""
elif [ "$per" -gt "0" ]; then
	icon=""
	notify-send -u critical "Battery Low" "Connect Charger"
else
        echo  && exit
fi
echo "$icon"
}

percent() {
echo $per
}

prof() {
	powerprofilesctl set $1
	eww update active-prof=$1
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
[ "$1" = "prof" ] && prof "$2" && exit
exit
